dev-java/istack-commons-runtime: Fix build under java 11
Remove module-info.java for now. It causes some odd circular issues
unsure of the fix at the moment. Attempts were unsuccessful thus
removing for now.

As is fails with

src/main/java/com/sun/istack/ByteArrayDataSource.java:43:
	error: package javax.activation is not visible
import javax.activation.DataSource;
            ^
  (package javax.activation is declared in the unnamed module, but
module javax.activation does not read it)

Package-Manager: Portage-2.3.36, Repoman-2.3.9