dev-java/checker-javacutil: Fix build under Java 10, drop class
Dropped ManualTaglet per the following
src/org/checkerframework/javacutil/dist/ManualTaglet.java:4: error:
package com.sun.tools.doclets does not exist
import com.sun.tools.doclets.Taglet;

Not sure what module exports that, if any. Tried a few, none worked.
Unless needed by something else, dropping for now.

Package-Manager: Portage-2.3.24, Repoman-2.3.6